### ISSUE TITLE
S-RTTI - Version for Lower Releases

### ISSUE THREAD

**Issue by oblomov-dev** [sandraros/S-RTTI#5]
Hi @sandraros,

Thank you for this great project and idea! I've been using it in abap2UI5, and it significantly streamlines the serialization process of the framework. Additionally, it provides end-users with the ability to easily work with attributes which are dynamically created during runtime.

The original repository works since ABAP 751 onward due to its use of ENUMs. Therefore I created an additional repository where I downported the syntax (thank you to @larshp and the tool @abaplint) to be compatible with versions lower than v.751 and removed the ENUM dependencies in this new version:
https://github.com/abap2UI5/S-RTTI-downport

I want to avoid creating redundant repository or projects, so let me know if i can send you a PR that you can integrate this as a separated branch to S-RTTI or want to have it as a separated project on your side.

Best regards.

**Comment by sandraros** [comment]
Thanks @oblomov-dev. That's a very good idea to have one branch per version. I could also merge some of your modifications in the main branch so that the code of all versions is the closest possible. I guess we could have another version for 7.40 too (removal of INT8). I'd like to setup abaplint but it's a new thing for me and never had the courage to do it.

How do you want to name the branches? (`7.50`? Maybe I would keep `main` for the latest version I can access to verify it works)

Thanks.

For information, I have this example of project with one branch per version and SP (SP needed here but with RTTI I guess we don't need to bother):
![image](https://github.com/sandraros/S-RTTI/assets/34005250/a7827fdb-5a49-4c65-951c-916a8dc2e6de)

**Comment by oblomov-dev** [comment]
Hi @sandraros,

branch names with the release as in the picture looks good i think. and yes i also forgot that we also have to take care of INT8, maybe four branches 7.3x (without INT8), 7.40 (with INT8), 7.51 (with INT8+ENUMS) and main is a good start?

For simplicity i deleted the unit tests in the downport, maybe it makes sence to keep them only in the main branch and do all testing with main. I will try to send you a PR next.

Best regards.

P.S.:
You can use abaplint for syntax downporting and for static code analysis. I used abaplint here to automatically downport the syntax. But this is done now, so no need to use abaplint a second time. But besides that if you want to try out abaplint for the static code analysis of the repository, you just need to active the abaplint app in the setup of GitHub and then add an abaplint.jsonc with all your rules as it is for example done [here.](https://github.com/abap2UI5/abap2UI5/blob/main/abaplint.jsonc) Feel free to give it a try,  I initially tried it a year ago and now find it immensely helpful in my work.

**Comment by sandraros** [comment]
Thanks. INT8 appeared in 7.50 so I created the branch `7.50`. I'll check #6 a little bit later, I will propose a commit to arrange the variable names.

NB: I also renamed the branch `master` to `main` ("members will have to manually update their local environments. We'll let them know when they visit the repository, or you can share the following commands.")
```
  git branch -m master master
  git fetch origin
  git branch -u origin/master master
  git remote set-head origin -a
```

**Comment by everton-demo** [comment]
Hi @sandraros ,
I'm starting to use the abap2UI5 project, on a system with version 7.31. @oblomov-dev kindly adapted it to earlier versions.
I installed your S-RTTI project, branch 7.50, but I found the error mentioned in this issue, referring to INT8. Are you thinking about making a new branch available that is compatible with lower systems?
Thanks

**Comment by sandraros** [comment]
@everton-demo I have created the branch [`7.40`](https://github.com/sandraros/S-RTTI/tree/7.40). It should not contain INT8 as it doesn't exist in 7.40. Would you mind proposing a pull request without INT8? Thank you!

**Comment by everton-demo** [comment]
Sorry, but I'm not that familiar with github, just starting to use it. I use the standalone version of abapGit, I'm not sure if I can do this through it, or does it need to be the full version. I even tried to stage and commit the 7.40 branch, but a pop-up appeared asking for credentials.

**Comment by sandraros** [comment]
Thanks. It's fine with ZABAPGIT_STANDALONE, it's fully operational, it just doesn't update "by itself". You may create a GitHub user account, setup an API key/Personal Access Token whose code will be your password, then "fork" the repository into your account. With ZABAPGIT_STANDALONE you may push ABAP code to your repository, you'll create a pull request from your repository which I can then merge. Don't hesitate to ask again if you need any detail.

**Comment by everton-demo** [comment]
Hi, I tried to do as advised, if need any further steps, I'm at your disposal. Thanks.
https://github.com/sandraros/S-RTTI/pull/9

**Comment by sandraros** [comment]
Thanks. For information, I had forgotten to include the abaplint configuration file, I'm restarting the abaplint check.

**Comment by everton-demo** [comment]
Hi, do I need to do anything?

**Comment by sandraros** [comment]
I had added the abaplint configuration file to the repository, but abaplint was still failing, I guess it was taking the file from your branch (i.e. none = default abaplint settings). I just merged. Thank you!

**Comment by oblomov-dev** [comment]
@sandraros thanks again for the release dependent branches, very useful, i close this one now.
